### ISSUE TITLE
Too Many & Too Few End Calls

### ISSUE THREAD

**Issue by madeinjei** [Michael-48/Iris#20]
Im trying to create this exact stack however I getting an error saying:
`Callback has too many calls to Iris.End()` or `To Few calls to Iris.End()` 
I tried to follow the demo you have on the docs page and then diagnose by looking at your source but I dont know why this is an issue.

```lua
Iris.Init()
	
	Iris:Connect(function()
		Iris.Window({"MENU", [Iris.Args.Window.NoResize] = true}, {size = Vector2.new(100, 100)})
		
		if Iris.Button({"Spawn"}).clicked() then
			
			
			RemotesManager.Client:Get("SpawnPlayer"):SendToServer()
			Iris.End()
		end
		
		Iris.End()
	end)
```

**Comment by JakeyWasTaken** [comment]
Iris.Button doesnt require an end.

**Comment by yaelvalle** [comment]
even so, I still end up with a too many end calls error

**Comment by Michael-48** [comment]
In the case that the button is clicked, Iris.End() is called twice, instead:
```
		if Iris.Button({"Spawn"}).clicked() then
			   -- call server
   end
   Iris.End()
	end)
```
Iris.End in branching code should only happen when a branch uses `break`, `return`, `continue`, etc.
there is another problem, though, sendToServer yields. If the yield lasts longer than an Iris cycle, The same error will pop up.
```
		if Iris.Button({"Spawn"}).clicked() then
        task.spawn(function()
			        -- call server
        end)
   end
   Iris.End()
	end)
```
I'm going to keep this issue opened because I think the behavior when attempting to yield should be improved, and should have an intuitive error.

**Comment by Michael-48** [comment]
> I'm going to keep this issue opened because I think the behavior when attempting to yield should be improved, and should have an intuitive error.

Ive made this change now: https://github.com/Michael-48/Iris/commit/e7bedd35d71196bae664f73375e6332040f6fb6e, closing the issue
