### ISSUE TITLE
open/close

### ISSUE THREAD

**Issue by splittable** [Michael-48/Iris#24]
no close keybind, or full close

**Comment by SirMallard** [comment]
Could you elaborate more?

Is this in reference to opening or closing specific windows which you create. If so, then there are multiple ways of checking if a key has been pressed.

**Comment by splittable** [comment]
> Could you elaborate more?
> 
> Is this in reference to opening or closing specific windows which you create. If so, then there are multiple ways of checking if a key has been pressed.

I mean to entirely close it off the screen, and to use a keybind to open back up.

**Comment by Michael-48** [comment]
I don't think this is a helpful addition, given the current maturity of Iris. 

- A goal of Iris is to be minimalistic and low overhead, claiming the keybind Ctrl+W, Ctrl+D, or even just Escape will undoubtedly cause issues when integrating Iris into existing projects.
- Windows which can be closed by the user are unintuitive to the coder, I would prefer to put as little emphasis on the Window Close functionality as reasonable. There are 2 levels of non-existence for a window, when it is called every cycle but its Closed state is true, and when the window is no longer called (Confusing ! ). This is why windows are made NoClose by default.
- This doesn't exist in Dear ImGui. Generally, the features added to Iris which aren't present in Dear ImGui are because they fine tune the library for use in Roblox and Luau. 

Similarly to this there is a keybind, Ctrl+Tab to swap windows like how Ctrl+Tab works in a browser, or Alt+Tab in windows.
Thanks for submitting the Issue!
